.TH "billboardObject" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
billboardObject \- la classe BillboardObject devait etre a la base capable d'afficher des billboard, mais par manque de temps, elle est capable de contenir uniquement la barre de vie\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <billboardobject\&.h>\fP
.PP
Est dérivée de \fBObject\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBbillboardObject\fP ()"
.br
.RI "Constructeur\&. "
.ti -1c
.RI "\fBbillboardObject\fP (\fBTransform\fP tt, \fBTransform\fP anim)"
.br
.RI "constructeur avec parametre "
.ti -1c
.RI "void \fBupdateScene\fP (double deltaTime, QMatrix4x4 m)"
.br
.RI "boucle de rendu, appel au parents "
.ti -1c
.RI "bool \fBUpdatebarreDeVie\fP (double deltaTime)"
.br
.RI "met a jour la bare de vie "
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "float \fBvie\fP = 100"
.br
.RI "vie point de vie du joueur, se dégrade au fil du temps "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
la classe BillboardObject devait etre a la base capable d'afficher des billboard, mais par manque de temps, elle est capable de contenir uniquement la barre de vie\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "billboardObject::billboardObject (\fBTransform\fP tt, \fBTransform\fP anim)\fC [inline]\fP"

.PP
constructeur avec parametre 
.PP
\fBParamètres\fP
.RS 4
\fItt\fP matrice de transformation 
.br
\fIanim\fP matrice d'animation 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "bool billboardObject::UpdatebarreDeVie (double deltaTime)"

.PP
met a jour la bare de vie 
.PP
\fBParamètres\fP
.RS 4
\fIdeltaTime\fP intervalle de temps depuis le dernier appel 
.RE
.PP
\fBRenvoie\fP
.RS 4
.RE
.PP

.SS "void billboardObject::updateScene (double deltaTime, QMatrix4x4 m)\fC [virtual]\fP"

.PP
boucle de rendu, appel au parents 
.PP
\fBParamètres\fP
.RS 4
\fIdeltaTime\fP intervalle de temps depuis le dernier appel 
.br
\fIm\fP matrice de transformation du parent 
.RE
.PP

.PP
Réimplémentée à partir de \fBObject\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
