.TH "billboardobject.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
billboardobject.h \- la classe BillboardObject devait etre a la base capable d'afficher des billboard, mais par manque de temps, elle est capable de contenir uniquement la barre de vie\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QVector4D>\fP
.br
\fC#include 'object\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbillboardObject\fP"
.br
.RI "la classe BillboardObject devait etre a la base capable d'afficher des billboard, mais par manque de temps, elle est capable de contenir uniquement la barre de vie\&. "
.in -1c
.SH "Description détaillée"
.PP 
la classe BillboardObject devait etre a la base capable d'afficher des billboard, mais par manque de temps, elle est capable de contenir uniquement la barre de vie\&. 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
