.TH "cameraobject.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cameraobject.h \- le fichier contient la classe \fBCameraObject\fP qui gère l'objet Caméra  

.SH SYNOPSIS
.br
.PP
\fC#include 'object\&.h'\fP
.br
\fC#include 'QVector3D'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameraObject\fP"
.br
.RI "la classe \fBCameraObject\fP qui gère l'objet Caméra "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBCameraObject\fP qui gère l'objet Caméra 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
