.TH "gameobject.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gameobject.h \- le fichier contient la classe \fBGameObject\fP contient les objets qui ne subisse pas la gravité, comme le terrain, le soleil, les arbres etc \&.\&.\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'transform\&.h'\fP
.br
\fC#include 'geometryengine\&.h'\fP
.br
\fC#include 'object\&.h'\fP
.br
\fC#include <QVector3D>\fP
.br
\fC#include <QVector4D>\fP
.br
\fC#include <QQuaternion>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QOpenGLTexture>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameObject\fP"
.br
.RI "la classe \fBGameObject\fP contient les objets qui ne subisse pas la gravité, comme le terrain, le soleil, les arbres etc \&.\&.\&. "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBGameObject\fP contient les objets qui ne subisse pas la gravité, comme le terrain, le soleil, les arbres etc \&.\&.\&. 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
