.TH "GameObject" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameObject \- la classe \fBGameObject\fP contient les objets qui ne subisse pas la gravité, comme le terrain, le soleil, les arbres etc \&.\&.\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gameobject\&.h>\fP
.PP
Est dérivée de \fBObject\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBGameObject\fP ()"
.br
.RI "ATTRIBUT\&. "
.ti -1c
.RI "\fBGameObject\fP (\fBTransform\fP tt, \fBTransform\fP anim)"
.br
.RI "constructeur avec parametre "
.ti -1c
.RI "void \fBupdateScene\fP (double deltaTime)"
.br
.RI "Getter/Setter\&. "
.ti -1c
.RI "void \fBupdateScene\fP (double deltaTime, QMatrix4x4 lastM) override"
.br
.RI "boucle de rendu, appel au parents "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
la classe \fBGameObject\fP contient les objets qui ne subisse pas la gravité, comme le terrain, le soleil, les arbres etc \&.\&.\&. 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "GameObject::GameObject ()\fC [inline]\fP"

.PP
ATTRIBUT\&. Constructeur
.PP
Constructeur 
.SS "GameObject::GameObject (\fBTransform\fP tt, \fBTransform\fP anim)\fC [inline]\fP"

.PP
constructeur avec parametre 
.PP
\fBParamètres\fP
.RS 4
\fItt\fP matrice de transformation 
.br
\fIanim\fP matrice d'animation 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "void GameObject::updateScene (double deltaTime)"

.PP
Getter/Setter\&. charge le shader, appelle la methode parent
.PP
Methode
.PP
boucle de rendu, appel recursif 
.PP
\fBParamètres\fP
.RS 4
\fIdeltaTime\fP intervalle de temps depuis le dernier appel
.br
\fIdeltaTime\fP intervalle de temps 
.RE
.PP

.SS "void GameObject::updateScene (double deltaTime, QMatrix4x4 lastM)\fC [override]\fP, \fC [virtual]\fP"

.PP
boucle de rendu, appel au parents 
.PP
\fBParamètres\fP
.RS 4
\fIdeltaTime\fP intervalle de temps depuis le dernier appel 
.br
\fIm\fP matrice de transformation du parent 
.RE
.PP

.PP
Réimplémentée à partir de \fBObject\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
