.TH "geometrymeshengine.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometrymeshengine.h \- le fichier contient la classe \fBGeometryMeshEngine\fP qui effectue toute les actions en rapport aux maillage importer  

.SH SYNOPSIS
.br
.PP
\fC#include 'geometryengine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertexDataWithNormal\fP"
.br
.ti -1c
.RI "class \fBGeometryMeshEngine\fP"
.br
.RI "la classe \fBGeometryMeshEngine\fP effectue toute les actions en rapport aux maillage importer "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBGeometryMeshEngine\fP qui effectue toute les actions en rapport aux maillage importer 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
