.TH "geometryUI" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometryUI \- la classe \fBgeometryUI\fP gère les maillage de type BillBoard  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometryui\&.h>\fP
.PP
Est dérivée de \fBGeometryMeshEngine\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBinitLifeBar\fP ()"
.br
.RI "virtual, voir BillboardObject::initLifeBar() "
.ti -1c
.RI "bool \fBupdateLifeBar\fP (double time)"
.br
.RI "virtual, voir BillboardObject::updateLifeBar() "
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
la classe \fBgeometryUI\fP gère les maillage de type BillBoard 
.SH "Documentation des fonctions membres"
.PP 
.SS "void geometryUI::initLifeBar ()\fC [virtual]\fP"

.PP
virtual, voir BillboardObject::initLifeBar() 
.PP
Réimplémentée à partir de \fBGeometryEngine\fP\&.
.SS "bool geometryUI::updateLifeBar (double deltaTime)\fC [virtual]\fP"

.PP
virtual, voir BillboardObject::updateLifeBar() 
.PP
Réimplémentée à partir de \fBGeometryEngine\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
