.TH "geometryengine.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometryengine.h \- le fichier contient la classe \fBGeometryEngine\fP qui effectue toute les actions en rapport aux maillage  

.SH SYNOPSIS
.br
.PP
\fC#include <QOpenGLFunctions_4_1_Core>\fP
.br
\fC#include <QOpenGLShaderProgram>\fP
.br
\fC#include <QOpenGLBuffer>\fP
.br
\fC#include <QtGui/QImage>\fP
.br
\fC#include <QVector2D>\fP
.br
\fC#include <QVector3D>\fP
.br
\fC#include 'BasicIO\&.h'\fP
.br
\fC#include 'transform\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertexData\fP"
.br
.ti -1c
.RI "struct \fBMinMax\fP"
.br
.RI "pour la boite englobante (uniquement utilisé pour les instances) "
.ti -1c
.RI "class \fBGeometryEngine\fP"
.br
.RI "la classe \fBGeometryEngine\fP effectue toute les actions en rapport aux maillage "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBGeometryEngine\fP qui effectue toute les actions en rapport aux maillage 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
