.TH "geometryui.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometryui.h \- le fichier contient la classe \fBgeometryUI\fP gère les maillage de type BillBoard  

.SH SYNOPSIS
.br
.PP
\fC#include 'geometrymeshengine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgeometryUI\fP"
.br
.RI "la classe \fBgeometryUI\fP gère les maillage de type BillBoard "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBgeometryUI\fP gère les maillage de type BillBoard 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
