.TH "mainwidget.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwidget.h \- la classe \fBMainWidget\fP est la classe principale qui contiens le graphe de scène et initialise la confiture  

.SH SYNOPSIS
.br
.PP
\fC#include 'geometryengine\&.h'\fP
.br
\fC#include 'geometrymeshengine\&.h'\fP
.br
\fC#include 'geometryui\&.h'\fP
.br
\fC#include 'gameobject\&.h'\fP
.br
\fC#include 'billboardobject\&.h'\fP
.br
\fC#include 'controler\&.h'\fP
.br
\fC#include 'mobileobj\&.h'\fP
.br
\fC#include 'cameraobject\&.h'\fP
.br
\fC#include <QOpenGLWidget>\fP
.br
\fC#include <QOpenGLFunctions>\fP
.br
\fC#include <QMatrix4x4>\fP
.br
\fC#include <QQuaternion>\fP
.br
\fC#include <QVector2D>\fP
.br
\fC#include <QBasicTimer>\fP
.br
\fC#include <QOpenGLShaderProgram>\fP
.br
\fC#include <QOpenGLTexture>\fP
.br
\fC#include <QElapsedTimer>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QToolTip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWidget\fP"
.br
.RI "la classe \fBMainWidget\fP est la classe principale qui contiens le graphe de scène et initialise la confiture "
.in -1c
.SH "Description détaillée"
.PP 
la classe \fBMainWidget\fP est la classe principale qui contiens le graphe de scène et initialise la confiture 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
