.TH "MinMax" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinMax \- pour la boite englobante (uniquement utilisé pour les instances)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <geometryengine\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "QVector3D \fBBBMin\fP =QVector3D(0,0,0)"
.br
.ti -1c
.RI "QVector3D \fBBBMax\fP = QVector3D(0,0,0)"
.br
.in -1c
.SH "Description détaillée"
.PP 
pour la boite englobante (uniquement utilisé pour les instances) 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
