.TH "mobileobj.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mobileobj.h \- le fichier contient la classe MobileObject contient les objets subissant la gravité, on peut y trouver le joueur, la boite\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QVector3D>\fP
.br
\fC#include 'transform\&.h'\fP
.br
\fC#include 'geometryengine\&.h'\fP
.br
\fC#include 'object\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMobileObj\fP"
.br
.RI "la classe MobileObject contient les objets subissant la gravité, on peut y trouver le joueur, la boite\&. "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe MobileObject contient les objets subissant la gravité, on peut y trouver le joueur, la boite\&. 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
