.TH "transform.h" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transform.h \- le fichier contient la classe \fBTransform\fP effectue les calculs géométrique afin de générer une matrice de tranformation à partir de scale, translate, rotation  

.SH SYNOPSIS
.br
.PP
\fC#include <QMatrix3x3>\fP
.br
\fC#include <QMatrix4x4>\fP
.br
\fC#include <QVector3D>\fP
.br
\fC#include <QVector4D>\fP
.br
\fC#include <QQuaternion>\fP
.br
\fC#include <QOpenGLBuffer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransform\fP"
.br
.RI "la classe \fBTransform\fP \fBTransform\fP effectue les calculs géométrique afin de générer une matrice de tranformation à partir de scale, translate, rotation "
.in -1c
.SH "Description détaillée"
.PP 
le fichier contient la classe \fBTransform\fP effectue les calculs géométrique afin de générer une matrice de tranformation à partir de scale, translate, rotation 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
