.TH "VertexDataWithNormal" 3 "Mercredi 12 Janvier 2022" "Moteur De Jeu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexDataWithNormal
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "QVector3D \fBposition\fP"
.br
.ti -1c
.RI "QVector2D \fBtexCoord\fP"
.br
.ti -1c
.RI "QVector3D \fBnormal\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Moteur De Jeu à partir du code source\&.
